FROM rockylinux:9.3
RUN dnf -y install gcc make
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

COPY . /build
RUN cd /build && ls && make install
